### ISSUE TITLE
n/a on location summary report

### ISSUE THREAD

**Issue by jpechmann** [agrc/ironing-board#102]
There is n/a on this report: http://locate.utah.gov/report.html?x=-12452357.550607217&y=4963770.7673308775&address=1047%20E%20Quail%20Vista%20Ln&city=%5Bno%20city%20found%5D&zip=84117&county=Salt%20Lake. It might be Zayo.

**Comment by stdavis** [comment]
The problem was that the provider's info was not in the `Database Connections\UBBMAP.sde\UBBMAP.UBBADMIN.BB_Providers_Table` table.

This table needs to be merged with `Database Connections\FiberVerification_PROD as FiberAdmin.sde\FiberVerification.FIBERADMIN.Providers`, however, I'm not sure how to work around the fact that `FiberVerification.FIBERADMIN.Providers` participates in a relationship.
