### ISSUE TITLE
Add RDAs (Tax Increment Zones)

### ISSUE THREAD

**Issue by BGranberg** [agrc/ironing-board#162]
In Test...

Change Work Force Layer to Economy

Add 'Tax Increment Areas' as a layer under Economy..they are accessible from Economy.TaxEntities2017 (this will need to be repointed in March of each year) with a filter for ENTNBR like '8%' or ENTNBR like '9%'

Add a section to the report that lists Enterprise Zones and Tax Increment Areas and contact info (forthcoming) for each of these sections.

**Comment by stdavis** [comment]
Hey @BGranberg: I've got this pushed to http://test.mapserv.utah.gov/bbecon/. Take a look and let me know what needs to be changed/updated.

I didn't include contact info for the TIAs since it's not in the data yet.

Also, I wondered if you wanted the tax increment areas and enterprise zones to be switched to radio buttons.
